// CategoryOneData.js
export const newsData = {
  feature: {
    id: 101,
    category: "daynightnews",
    title: "Xiaomi Pad 7 के बारे में तो आपने काफी चर्चा सुनी होंगी….",
    summary: "आज हम आपको इस पैड के बारे में जानकारी देने जा...",
    imageUrl: "https://daynightnews.in/wp-content/uploads/2025/01/img9.jpg",
    time: "2:00 PM",
    date: "August 16, 2022",
    comments: 210,
  },
  business: [
    {
      id: 102,
      category: "daynightnews",
      title: "World tranding best 10 website travel tips for runners groups of",
      summary: "He legged it say sloshed eaton bugger bobby that about crikey...",
      imageUrl: "https://daynightnews.in/wp-content/uploads/2022/08/19.jpg",
      time: "12:00 PM",
      date: "August 16, 2022",
      comments: 90,
    },
    {
      id: 103,
      category: "daynightnews",
      title: "Selective focus photography of orange fox life",
      summary: "He legged it say sloshed eaton bugger bobby that about crikey...",
      imageUrl: "https://daynightnews.in/wp-content/uploads/2022/08/9.jpg",
      time: "10:30 AM",
      date: "August 16, 2022",
      comments: 55,
    },
  ],
  it: [
    {
      id: 104,
      category: "",
      title: "Need some fresh air",
      summary: "He legged it say sloshed eaton bugger bobby that about crikey...",
      imageUrl: "https://daynightnews.in/wp-content/uploads/2022/08/6-1.jpg",
      time: "09:00 AM",
      date: "August 16, 2022",
      comments: 130,
    },
    {
      id: 105,
      category: "",
      title: "Top 20 best thems plugn & on this year visit",
      summary: "He legged it say sloshed eaton bugger bobby that about crikey...",
      imageUrl: "https://daynightnews.in/wp-content/uploads/2022/08/13.jpg",
      time: "07:00 AM",
      date: "August 16, 2022",
      comments: 72,
    },{
      id: 106,
      category: "",
      title: "Running on the field whether you travel for work",
      summary: "He legged it say sloshed eaton bugger bobby that about crikey...",
      imageUrl: "https://daynightnews.in/wp-content/uploads/2022/08/4-2.jpg",
      time: "07:00 AM",
      date: "August 16, 2022",
      comments: 72,
    },
  ],
  states: [
    { name: "Maharashtra", slug: "maharashtra" },
    { name: "Gujarat", slug: "gujarat" },
    { name: "Tamil Nadu", slug: "tamil-nadu" },
    { name: "West Bengal", slug: "west-bengal" },
    { name: "Karnataka", slug: "karnataka" },
    { name: "Uttar Pradesh", slug: "uttar-pradesh" },
    { name: "Kerala", slug: "kerala" },
    { name: "Rajasthan", slug: "rajasthan" },
  ],
};